// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace HorseService.Models
{
    public partial class Configuration
    {
        [Key]
        public int ConfigurationId { get; set; }
        public double Cost { get; set; }
    }
}