// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace HorseService.Models
{
    public partial class ContactUs
    {
        public int ContactUsId { get; set; }
        [Required]
        public string CompanyName { get; set; }
        [RegularExpression("^[0-9]+$", ErrorMessage = " Accept Number Only")]
        public string Tele { get; set; }
        public string Fax { get; set; }
        [Required]
        [RegularExpression("^[0-9]+$", ErrorMessage = " Accept Number Only")]
        public string Mobile { get; set; }
        [EmailAddress]
        [Required, RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$", ErrorMessage = "Not Valid")]
        public string Email { get; set; }
        [Required]
        public string Address { get; set; }
        public string Facebook { get; set; }
        [RegularExpression("^[0-9]+$", ErrorMessage = " Accept Number Only")]
        public string WhatsApp { get; set; }
        public string LinkedIn { get; set; }
        public string Instgram { get; set; }
        public string Twitter { get; set; }
    }
}