// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace HorseService.Models
{
    public partial class Customer
    {
        public Customer()
        {
           
            Appointments = new HashSet<Appointments>();
          
           
        }

        public int CustomerId { get; set; }
       
        [Required]
        public string CustomerNameEn { get; set; }
       
        [Required]
        [RegularExpression("^[0-9]+$", ErrorMessage = " Accept Number Only")]
        public string CustomerPhone { get; set; }
        //[EmailAddress]
        //[Required, RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$", ErrorMessage = "Not Valid")]
        //public string CustomerEmail { get; set; }
        public string CustomerImage { get; set; }
        //public string CustomerRemarks { get; set; }

        public virtual ICollection<Appointments> Appointments { get; set; }
       

    }
}